### ISSUE TITLE
RSS: Voskhod-3KV-No.2.cfg empty file

### ISSUE THREAD

**Issue by Gordon-Dry** [Frylovespi/History-of-Spaceflight#10]
That is just a zero byte file.

I don't know if it should be deleted or if you forgot something.

RSS:
GameData\ContractPacks\HistoryofSpaceflight\Missions\SovietMissions\Voskhod\Voskhod-3KV-No.2.cfg

**Comment by Frylovespi** [comment]
I know there is a reason I made it, but can't for the life of me remember why. Oh well, for now you can delete it and if I figure out if it is needed I will add it back in.
