### ISSUE TITLE
Impossible mission in stock - orbit with apogee lower than 70km

### ISSUE THREAD

**Issue by Searcher-M** [Frylovespi/History-of-Spaceflight#28]
https://github.com/Frylovespi/History-of-Spaceflight/blob/ebe4f8a4f00850cf28d6a96a73234a8bbb88b33e/Stock/GameData/ContractPacks/HistoryofSpaceflight/Missions/USAMissions/MannedMissions/GeminiMissions/Gemini-XI.cfg#L120

Gemini-XI requires to lower apogee to lower than 70 km in stock game while staying in orbit that is impossible.

**Comment by Morphisor244** [comment]
It shouldn't require that and as far as I can tell right now the associated lines look ok, defaulting to the space altitude if a value lower than that would otherwise be required. Can you provide screenshot(s) of the erroneous behaviour?

**Comment by Morphisor244** [comment]
Had another look and noticed the value was written as a max value, which means the space altitude was defined as maximum altitude and made orbit to be impossible indeed. It's now fixed on the GitHub branch. Thanks for catching that, surprised it hasn't come to light sooner.
