### ISSUE TITLE
Kosmos-34 has requirement on its own

### ISSUE THREAD

**Issue by rzabcio** [Frylovespi/History-of-Spaceflight#3]
This blocks progress and creates situation when US Surveyor-1 is BEFORE Luna-9.

https://github.com/Frylovespi/History-of-Spaceflight/blob/master/Stock/ContractPacks/HistoryofSpaceflight/Missions/SovietMissions/Kosmos/Kosmos%201-40/Kosmos-34.cfg
~~~~
REQUIREMENT
{
          name = PreviousMission
          type = CompleteContract
          contractType = Kosmos-34
          minCount =1
          maxCount =1
          cooldownDuration = 0d
}
~~~~

**Comment by rzabcio** [comment]
Damn, forgot to mention it's about stock version.

**Comment by Frylovespi** [comment]
Thanks for pointing that out and sorry for the late reply.

Fixed on github. Clone to download and install. Will be added to a hotfix release in the coming days

**Comment by wolffy-au** [comment]
Same issue in RSS. I'm on V0.9.2 from CKAN.

**Comment by Morphisor244** [comment]
> Same issue in RSS. I'm on V0.9.2 from CKAN.

Good spot, fix is up on the M_dev branch.
