### ISSUE TITLE
Kosmos-41 has description 'Kosmos-40'

### ISSUE THREAD

**Issue by rzabcio** [Frylovespi/History-of-Spaceflight#5]
This block progress, because requirement for 'Kosmos-41' can be never met.
https://github.com/Frylovespi/History-of-Spaceflight/blob/master/Stock/ContractPacks/HistoryofSpaceflight/Missions/SovietMissions/Kosmos/Kosmos%2041-80/Kosmos-41.cfg

~~~~
CONTRACT_TYPE
{
         name = Kosmos-40
         group= KosmosMission
		
         title = Kosmos-40
~~~~

Should be:
~~~~
CONTRACT_TYPE
{
         name = Kosmos-41
         group= KosmosMission
		
         title = Kosmos-41
~~~~

**Comment by rzabcio** [comment]
Similar situation with Kosmos-48 and Kosmos-49.

**Comment by Gordon-Dry** [comment]
Damnit - too much copy and paste with out reading it ... and then releasing.

**Comment by rzabcio** [comment]
Yeah, lookin at the files I can tell where did it come from. :)

Maybe I will send you changed files after I make corrections? What do you think? I tried to fork the repo, but I have differences on whole files, probably end lines encoding... :-\

**Comment by Gordon-Dry** [comment]
When you find more you can send them, just put a dropbox link here.

If I don't have encoding issues I will create a PR then.
If I have encoding issues, it lasts longer... ;)

**Comment by Frylovespi** [comment]
Fixed on github. Clone to download and install. Will be added to a hotfix release in the coming days
