### ISSUE TITLE
Dongfeng-4 depends on non-existent Explorer-40

### ISSUE THREAD

**Issue by rzabcio** [Frylovespi/History-of-Spaceflight#9]
Probably this will be auto-fixed when there will be more Explorers missions, but for now Donfeng-4, -4A and -4B mission cannot be accepted.

This is the only bug in missions for now - I have done all other missions (beside Dongfeng-4 series). Other problem are corrected in my pull-request (just some simple requirements).

**Comment by Gordon-Dry** [comment]
Let's set them too Explorer 35 then as long as there are no missions with higher numbers.

**Comment by Frylovespi** [comment]
Nice catch. Yes was planned for the eventual addition of Explorer-40 but for now Explorer-35 will do until more missions are added.

-Updated on Github.
